### PR TITLE
Update preflight with ergonomics changes

### PR DESCRIPTION
**Pull request by ba-edb**
@xugy99, @Anhui-tqhuang: I spent some time working with the Cloud Architects today on the onboarding process and I'd like to propose some changes to how the preflight script fits together. This PR sketches out the beginning of it by rewriting the `--help`; essentially I think we should split the script between two core use-cases: onboarding and productive-use.

Rather than using the `--with-infra` flag to add the DP overhead, the `--onboard` flag should check that the subscription is configured correctly, and that there is enough quota for a DP and a single non-HA E2s_v3 cluster. The customer should be able to do something like `curl raw.githubusercontent.com/azure-preflight | bash -s -- $SUBSCRIPTION $REGION` in their Azure web CLI and be off and running.

The other options remain for customers that are up and running but want to make sure that they have enough capacity to provision a new cluster. I don't think this second use case is ideal long-term - we want the portal/API to provide all the feedback the customer needs here.

I have a few other proposals to codify as well - e.g., you'll note here that I'm requiring `<target-subscription>` rather than assuming the default subscription in `az` is the target - but I'd like to get this first, largest change out there first to see what you guys think.

### CODE REVIEW

**Comment by Anhui-tqhuang** [comment]
onboarding seems like a init step when customer first uses our services, in your case, onboarding is related to a specific region which makes me a bit confused 🤔

**Comment by xugy99** [comment]
this looks good to me as a *pre-first-flight* check:
- user has to know which subscription is going to be used
- user has to know the first region it prefers for flight

@ba-edb do you want us to continue on patching to your branch?

**Comment by ba-edb** [comment]
> onboarding seems like a init step when customer first uses our services, in your case, onboarding is related to a specific region which makes me a bit confused

The onboarding follows a specific script; I'm suggesting we try to make that as simple as possible with this script. But you're right about needing to preflight a second region - we still need the `--infra` option. Will amend.

**Comment by ba-edb** [comment]
> @ba-edb do you want us to continue on patching to your branch?

Sure! I'm going to poke at this a bit more over the next couple of days as well. Thanks Guang.

**Comment by fisher046** [comment]
@xugy99 I rebased this PR with main branch and made some tiny fix for the conflicts with @Simonzhaohui's comments. I also add an option `--onboard` based on the initial @ba-edb's comment.

@ba-edb @xugy99 I set this PR to `read for review`. Could you provide some comments for it?

**Pull request merged**
